### ISSUE TITLE
Incorrect state shown even when files accepted

### ISSUE THREAD

**Issue by sankargorthi** [okonet/react-dropzone#330]
Hosted a demo here: https://github.com/sankargorthi/react-webpack-babel

Drag an image over the dropzone. The "rejected" class is applied in either case:

![dropzone error](https://cloud.githubusercontent.com/assets/924700/21952014/1c9b2fa4-d9c6-11e6-8886-def45bdf1e5a.gif)

### Relevant code

```js
onDrop(files, rejected) {
  console.log('Got these files:', files);
  console.log('Rejected these files:', rejected);
}

render() {
  return (
    <Dropzone accept=".jpg,.png"
        className={styles["drop-zone"]}
        activeClassName={styles["drop-zone-active"]}
        rejectClassName={styles["drop-zone-reject"]}
        multiple={false}
        onDrop={this.onDrop}>
      <div>Drop your files here</div>
  </Dropzone>
  );
}
```

```css
.drop-zone {
  color: green;
  padding: 20px;
  border: 1px dashed black;
}
.drop-zone.drop-zone-accept {
  color: white;
  background-color: green;
}
.drop-zone.drop-zone-reject {
  color: white;
  background-color: red;
}
```
